---
# tasks file for ansible-role-pdsh-genders
#

 - name: remove pdsh modules conflicting with genders
   package: name={{ pdsh_genders_conflict }} state=absent

 - name: install pdsh and dependencies EL7
   package: name={{ pdsh_el7_packages }} state=installed
   when: ansible_distribution_major_version == "7"

 - name: install pdsh and dependencies EL6
   package: name={{ pdsh_el6_packages }} state=installed
   when: ansible_distribution_major_version == "6"
